import type { Metadata } from 'next'
import { Pacifico, Roboto } from 'next/font/google'
import { Toaster } from 'sonner'
import RootProvider from '../providers/root.provider'
import '../assets/globals.css'

const roboto = Roboto({
	variable: '--font-roboto',
	subsets: ['latin', 'cyrillic']
})

const pacifico = Pacifico({
	variable: '--font-pacifico',
	weight: ['400'],
	subsets: ['latin', 'cyrillic']
})

export const metadata: Metadata = {
	title: 'Taskflow',
	description: 'Generated by create next app'
}

export default function BaseLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang='en'
			className={`${roboto.variable} ${pacifico.variable} h-full antialiased`}
		>
			<body>{children}</body>
		</html>
	)
}
