import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './assets/globals.css'
import { Header } from '@/widgets/header'
import { Footer } from '@/widgets/footer'

const roboto = Roboto({
	variable: '--font-roboto',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Taskflow',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' className={`${roboto.variable} h-full antialiased`}>
			<body className='min-h-full flex flex-col'>
				<Header />
				<main className='flex-1 relative'>{children}</main>
				<Footer />
			</body>
		</html>
	)
}
