import { PropsWithChildren } from 'react'
import BaseLayout from './layouts/BaseLayout'
import { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Taskflow',
	description: 'Generated by create next app'
}

export default function Layout({ children }: PropsWithChildren) {
	return <BaseLayout>{children}</BaseLayout>
}
